# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
      build:
        runs-on: ubuntu-latest
    
        steps:
          - name: checkout repo content
            uses: actions/checkout@v2 # checkout the repository content to github runner.
          - name: setup python
            uses: actions/setup-python@v2
            with:
              python-version: 3.8 #install the python needed
          - name: install pymongo # run the run.py to get the latest data
            run: |
             pip install pymongo
             pip install dnspython
             pip install requests
          - name: execute py script # run the run.py to get the latest data
            run: |
              python ./analysis/test.py ${{secrets.DBURI}} ${{secrets.BACKEND_TAGGER}}
          - name: Commit files
            id: commit
            run: |
              git config --local user.email "action@github.com"
              git config --local user.name "github-actions"
              git add --all
              if [-z "$(git status --porcelain)"]; then
                 echo "::set-output name=push::false"
              else
                 git commit -m "Add changes" -a
                 echo "::set-output name=push::true"
              fi
            shell: bash
          - name: Push changes
            if: steps.commit.outputs.push == 'true'
            uses: ad-m/github-push-action@master
            with:
               github_token: ${{ secrets.GITHUB_TOKEN }}
               
          - name: Checkout publish repo
            uses: actions/checkout@v2
            with:
              repository: 'sneblina/visualtag'
              ref: 'test'
              path: 'publish'
              persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
              fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

          - name: Clean publish repo
            working-directory: 'publish'
            run: |
              git rm -rf .
              git clean -fxd
          - name: Set up Node.js
            uses: actions/setup-node@v1
            with:
              node-version: '12.x'

          - name: Copy build
            run: 'cp -r chem_cluster.json publish'

          - name: Check for changes
            working-directory: publish
            run: |
              git add .
              git status
              [[ -z $(git status --porcelain) ]] || echo "::set-output name=changed::true"
            id: check_changes

          - name: Update publish repo
            if: steps.check_changes.outputs.changed
            working-directory: publish
            run: |
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git commit -m "Deploy $GITHUB_SHA"
          - name: Deploy to Pages
            if: steps.check_changes.outputs.changed
            uses: ad-m/github-push-action@v0.6.0
            with:
              directory: publish
              repository: sneblina/visualtag
              branch: test
              github_token: ${{ secrets.GITHUB_TOKEN }}
